### ISSUE TITLE
[crash] TypeError: options.colorFns.feature is not a function

### ISSUE THREAD

**Issue by fmagaldea** [kozhevnikov/cucumber-pretty#3]
As of:
* node js 9.8.0 (same error with 8.9.4)
* running on a mac
* package dependencies:
```
  "dependencies": {
    ...
    "bluebird": "3.5.1",
    ...
    "cucumber": "4.0.0",
    "cucumber-pretty": "1.4.0",
    ...
  }
```

While executing command:
```
./node_modules/.bin/cucumber-js -f node_modules/cucumber-pretty
```

I got and error, which full stack trace is:
```
TypeError: options.colorFns.feature is not a function
at EventEmitter.PrettyFormatter.options.eventBroadcaster.on (/workspace/my-project/node_modules/cucumber-pretty/index.js:66:39)
at EventEmitter.emit (events.js:180:13)
at TestCaseRunner.emit (/workspace/my-project/node_modules/cucumber/lib/runtime/test_case_runner.js:94:29)
at TestCaseRunner.<anonymous> (/workspace/my-project/node_modules/cucumber/lib/runtime/test_case_runner.js:217:14)
at Generator.next (<anonymous>)
at Generator.tryCatcher (/workspace/my-project/node_modules/bluebird/js/release/util.js:16:23)
at PromiseSpawn._promiseFulfilled (/workspace/my-project/node_modules/bluebird/js/release/generators.js:97:49)
at TestCaseRunner.<anonymous> (/workspace/my-project/node_modules/bluebird/js/release/generators.js:201:15)
at TestCaseRunner.run (/workspace/my-project/node_modules/cucumber/lib/runtime/test_case_runner.js:233:22)
at Runtime.<anonymous> (/workspace/my-project/node_modules/cucumber/lib/runtime/index.js:113:51)
at Generator.next (<anonymous>)
at Generator.tryCatcher (/workspace/my-project/node_modules/bluebird/js/release/util.js:16:23)
at PromiseSpawn._promiseFulfilled (/workspace/my-project/node_modules/bluebird/js/release/generators.js:97:49)
at Runtime.<anonymous> (/workspace/my-project/node_modules/bluebird/js/release/generators.js:201:15)
at Runtime.runTestCase (/workspace/my-project/node_modules/cucumber/lib/runtime/index.js:123:22)
at tryCatcher (/workspace/my-project/node_modules/bluebird/js/release/util.js:16:23)
at Object.gotValue (/workspace/my-project/node_modules/bluebird/js/release/reduce.js:155:18)
at Object.gotAccum (/workspace/my-project/node_modules/bluebird/js/release/reduce.js:144:25)
at Object.tryCatcher (/workspace/my-project/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/workspace/my-project/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/workspace/my-project/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/workspace/my-project/node_modules/bluebird/js/release/promise.js:606:10)
```

**Comment by kozhevnikov** [comment]
Could you please

1. Check what version of `colors` dependency you have installed in `node_modules/colors/package.json`. Also what versions are specified in `package-lock.json` or `yarn.lock`?

2. Add `console.log(options.colorFns);` after `options.colorFns.setTheme(theme);` on line 51 in `node_modules/cucumber-pretty/index.js` and post the output.

**Comment by fmagaldea** [comment]
Fyi I tested with colors version 1.1.2 and it doesn't crash so it's probably related to their recent release few days ago ?

1. My whole dependencies :
```
"dependencies": {
    "biguint-format": "1.0.0",
    "bluebird": "3.5.1",
    "bluebird-retry": "0.11.0",
    "chai": "4.1.2",
    "chai-as-promised": "7.1.1",
    "colors": "1.2.1",
    "cucumber": "4.0.0",
    "cucumber-pretty": "1.4.0",
    "dotenv": "5.0.1",
    "faker": "4.1.0",
    "flake-idgen": "1.1.0",
    "getenv": "0.7.0",
    "lodash": "4.17.5",
    "prettyjson": "1.2.1",
    "request": "2.85.0",
    "request-promise": "4.2.2",
    "sanitize-filename": "1.6.1",
    "selenium-webdriver": "3.6.0",
    "shortid": "2.2.8"
  }
```

List of yarn mentions about colors package :
```
...
cli-table2@0.2.0:
  version "0.2.0"
  resolved "https://registry.yarnpkg.com/cli-table2/-/cli-table2-0.2.0.tgz#2d1ef7f218a0e786e214540562d4bd177fe32d97"
  dependencies:
    lodash "^3.10.1"
    string-width "^1.0.1"
  optionalDependencies:
    colors "^1.1.2"

cli-table@^0.3.1:
  version "0.3.1"
  resolved "https://registry.yarnpkg.com/cli-table/-/cli-table-0.3.1.tgz#f53b05266a8b1a0b934b3d0821e6e2dc5914ae23"
  dependencies:
    colors "1.0.3"
...
colors@1.0.3:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/colors/-/colors-1.0.3.tgz#0433f44d809680fdeb60ed260f1b0c262e82a40b"

colors@1.1.2:
  version "1.1.2"
  resolved "https://registry.yarnpkg.com/colors/-/colors-1.1.2.tgz#168a4701756b6a7f51a12ce0c97bfa28c084ed63"

colors@1.2.1, colors@^1.1.2:
  version "1.2.1"
  resolved "https://registry.yarnpkg.com/colors/-/colors-1.2.1.tgz#f4a3d302976aaf042356ba1ade3b1a2c62d9d794"
...
cost-of-modules@1.0.1:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/cost-of-modules/-/cost-of-modules-1.0.1.tgz#f926126b553ccf0de3a998ab79ae738241525ed3"
  dependencies:
    ansi-regex "2.0.0"
    cli-table2 "0.2.0"
    colors "1.1.2"
    fs-extra "2.1.0"
    sync-exec "0.6.2"
    yargs-parser "4.0.2"
...
cucumber@4.0.0, cucumber@^4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/cucumber/-/cucumber-4.0.0.tgz#09f078b852d817c8f818737d0dcc34d40f31534f"
  dependencies:
    assertion-error-formatter "^2.0.1"
    babel-runtime "^6.11.6"
    bluebird "^3.4.1"
    cli-table "^0.3.1"
    colors "^1.1.2"
    commander "^2.9.0"
    cucumber-expressions "^5.0.7"
    cucumber-tag-expressions "^1.1.1"
    duration "^0.2.0"
    escape-string-regexp "^1.0.5"
    figures "2.0.0"
    gherkin "^5.0.0"
    glob "^7.0.0"
    indent-string "^3.1.0"
    is-generator "^1.0.2"
    is-stream "^1.1.0"
    lodash "^4.17.4"
    mz "^2.4.0"
    progress "^2.0.0"
    resolve "^1.3.3"
    stack-chain "^2.0.0"
    stacktrace-js "^2.0.0"
    string-argv "0.0.2"
    title-case "^2.1.1"
    util-arity "^1.0.2"
    verror "^1.9.0"
...
prettyjson@1.2.1:
  version "1.2.1"
  resolved "https://registry.yarnpkg.com/prettyjson/-/prettyjson-1.2.1.tgz#fcffab41d19cab4dfae5e575e64246619b12d289"
  dependencies:
    colors "^1.1.2"
    minimist "^1.2.0"
...
```

2. Output of console.log(options.colorFns); put in line 52 :
```
{ themes: {},
  styles:
   { reset: [ open: '\u001b[0m', close: '\u001b[0m', closeRe: /[0m/g ],
     bold: [ open: '\u001b[1m', close: '\u001b[22m', closeRe: /[22m/g ],
     dim: [ open: '\u001b[2m', close: '\u001b[22m', closeRe: /[22m/g ],
     italic: [ open: '\u001b[3m', close: '\u001b[23m', closeRe: /[23m/g ],
     underline: [ open: '\u001b[4m', close: '\u001b[24m', closeRe: /[24m/g ],
     inverse: [ open: '\u001b[7m', close: '\u001b[27m', closeRe: /[27m/g ],
     hidden: [ open: '\u001b[8m', close: '\u001b[28m', closeRe: /[28m/g ],
     strikethrough: [ open: '\u001b[9m', close: '\u001b[29m', closeRe: /[29m/g ],
     black: [ open: '\u001b[30m', close: '\u001b[39m', closeRe: /[39m/g ],
     red: [ open: '\u001b[31m', close: '\u001b[39m', closeRe: /[39m/g ],
     green: [ open: '\u001b[32m', close: '\u001b[39m', closeRe: /[39m/g ],
     yellow: [ open: '\u001b[33m', close: '\u001b[39m', closeRe: /[39m/g ],
     blue: [ open: '\u001b[34m', close: '\u001b[39m', closeRe: /[39m/g ],
     magenta: [ open: '\u001b[35m', close: '\u001b[39m', closeRe: /[39m/g ],
     cyan: [ open: '\u001b[36m', close: '\u001b[39m', closeRe: /[39m/g ],
     white: [ open: '\u001b[37m', close: '\u001b[39m', closeRe: /[39m/g ],
     gray: [ open: '\u001b[90m', close: '\u001b[39m', closeRe: /[39m/g ],
     grey: [ open: '\u001b[90m', close: '\u001b[39m', closeRe: /[39m/g ],
     bgBlack: [ open: '\u001b[40m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgRed: [ open: '\u001b[41m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgGreen: [ open: '\u001b[42m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgYellow: [ open: '\u001b[43m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgBlue: [ open: '\u001b[44m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgMagenta: [ open: '\u001b[45m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgCyan: [ open: '\u001b[46m', close: '\u001b[49m', closeRe: /[49m/g ],
     bgWhite: [ open: '\u001b[47m', close: '\u001b[49m', closeRe: /[49m/g ],
     blackBG: [ open: '\u001b[40m', close: '\u001b[49m', closeRe: /[49m/g ],
     redBG: [ open: '\u001b[41m', close: '\u001b[49m', closeRe: /[49m/g ],
     greenBG: [ open: '\u001b[42m', close: '\u001b[49m', closeRe: /[49m/g ],
     yellowBG: [ open: '\u001b[43m', close: '\u001b[49m', closeRe: /[49m/g ],
     blueBG: [ open: '\u001b[44m', close: '\u001b[49m', closeRe: /[49m/g ],
     magentaBG: [ open: '\u001b[45m', close: '\u001b[49m', closeRe: /[49m/g ],
     cyanBG: [ open: '\u001b[46m', close: '\u001b[49m', closeRe: /[49m/g ],
     whiteBG: [ open: '\u001b[47m', close: '\u001b[49m', closeRe: /[49m/g ] },
  supportsColor: [Function: getSupportLevel],
  enabled: true,
  strip: [Function],
  stripColors: [Function],
  stylize: [Function: stylize],
  setTheme: [Function],
  trap: [Function: runTheTrap],
  zalgo: [Function: zalgo],
  maps:
   { america: [Function],
     zebra: [Function],
     rainbow: [Function],
     random: [Function] },
  america: [Function],
  zebra: [Function],
  rainbow: [Function],
  random: [Function],
  ambiguous: { [Function: builder] _styles: [ 'red' ] },
  failed: { [Function: builder] _styles: [ 'red' ] },
  passed: { [Function: builder] _styles: [ 'green' ] },
  pending: { [Function: builder] _styles: [ 'yellow' ] },
  skipped: { [Function: builder] _styles: [ 'cyan' ] },
  undefined: { [Function: builder] _styles: [ 'yellow' ] },
  location: { [Function: builder] _styles: [ 'grey' ] },
  tag: { [Function: builder] _styles: [ 'cyan' ] },
  step: { [Function: builder] _styles: [ 'bold' ] } }
```

Thanks for your help.

**Comment by kozhevnikov** [comment]
I can't replicate the error, tried every version of `colors` from 1.2.1 to 1.0.0. Could you please create a new project with 1 feature that throws this error and push it to GitHub including the node_modules folder?

**Comment by fmagaldea** [comment]
To replicate the error, you can add in the file world:
```
const colors = require('colors');
colors.red('test');
```

I found that most of the time we were including colors like this:
```
const colors = require('colors/safe');
```
but 1 time it was included without '/safe':
```
const colors = require('colors');
```

Adding '/safe' in all colors inclusion fixed the crash.
From colors doc, using '/safe "doesn't extend String.prototype".
But they probably changed something in their last version because with the previous one I had no crash.

**Comment by kozhevnikov** [comment]
Please update to 1.4.1

**Comment by fmagaldea** [comment]
Works regardless usage or not of safe mode of 'colors' 1.2 thanks a lot !
