### ISSUE TITLE
Puppeteer errors when using cucumber-pretty

### ISSUE THREAD

**Issue by christopher-francisco** [kozhevnikov/cucumber-pretty#6]
I just added `cucumber-pretty@1.4.4`, to work with `cucumber@4.2.1`.  Previously my 2 test cases were passing, now one of them is failing with:

```
    ✖ failed
      Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
          at Promise (/my-project/node_modules/puppeteer/lib/Connection.js:200:56)
          at new Promise (<anonymous>)
          at CDPSession.send (/my-project/node_modules/puppeteer/lib/Connection.js:199:12)
          at ExecutionContext.evaluateHandle (/my-project/node_modules/puppeteer/lib/ExecutionContext.js:73:75)
          at ExecutionContext.evaluate (/my-project/node_modules/puppeteer/lib/ExecutionContext.js:46:31)
          at Frame.evaluate (/my-project/node_modules/puppeteer/lib/FrameManager.js:326:20)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
```

I'm calling it with:

```json
    "test": "cucumber-js -f node_modules/cucumber-pretty"
```

Any ideas?

**UPDATE:** this happens about 50% of the times I run it. The other half the tests pass

**Comment by kozhevnikov** [comment]
Can you create a sample test project exhibiting this error? The one I've created works fine and there's nothing in the stack trace to connect it to the formatter.
